### ISSUE TITLE
Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>

### ISSUE THREAD

**Issue by Ln2be** [holytrips/react-leaflet-marker#4]
using the example in this project readme give me this error

**Comment by vkruglikov** [comment]
@Ln2be let me know version react-leaflet , react-leaflet-marker

**Comment by Ln2be** [comment]
Thank you VKruglikov this is no longer relevant to me. I stopped using leaflet altogether.

**Comment by pLavrenov** [comment]
"react": "^18.2.0",
"react-leaflet": "^4.2.0",
"react-leaflet-marker": "^2.0.0",
