### ISSUE TITLE
Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>

### ISSUE THREAD

**Issue by pLavrenov** [holytrips/react-leaflet-marker#5]
"react": "^18.2.0",
"react-leaflet": "^4.2.0",
"react-leaflet-marker": "^2.0.0",

**Comment by xXBlackBulletXx** [comment]
@pLavrenov 
Hi, i've fixed the problem on my fork to work with `react-leaflet: 4.2.0` you can try installing from repo with 
`yarn add react-leaflet-marker-test`
or 
`npm i react-leaflet-marker-test`
meanwhile pr will be closed

**Comment by vkruglikov** [comment]
Thank you @pLavrenov  for your report and @xXBlackBulletXx  for contribution  :)
I am preparing https://github.com/holytrips/react-leaflet-marker/pull/7 RC with new version

**Comment by vkruglikov** [comment]
https://github.com/holytrips/react-leaflet-marker/pull/7
